export { default as SystemSettingsPage }    from './pages/SystemSettingsPage'
export { default as RolesPage }             from './pages/RolesPage'
export { default as PermissionsPage }       from './pages/PermissionsPage'
export { default as PlatformSettingsPage }  from './pages/PlatformSettingsPage'
export { default as UserRolePage }          from './pages/UserRolePage'
export { default as CollegeManagementPage } from './pages/CollegeManagementPage'
export { default as CollegeProfilePage }    from './pages/CollegeProfilePage'
export { default as FeatureFlagsPage }      from './pages/FeatureFlagsPage'
export { default as SettingsLayout }        from './layout/SettingsLayout'
export { settingsService }                  from './api/settingsApi'
export { rolesService }                     from './api/rolesApi'
export { collegeService }                   from './api/collegeApi'
export { collegeProfileService }            from './api/collegeProfileApi'
export { featureFlagsService }              from './api/featureFlagsApi'
